// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchoolAttendanceSystem.DAL.Data;

#nullable disable

namespace SchoolAttendanceSystem.DAL.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230503131344_UpdateTeacherTable")]
    partial class UpdateTeacherTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Roles", "security");

                    b.HasData(
                        new
                        {
                            Id = "c7dedf49-21a9-4f26-8c00-eadd86eb812f",
                            ConcurrencyStamp = "929f3c01-f56e-45fb-80e5-59460195b908",
                            Name = "SuperAdmin",
                            NormalizedName = "SUPERADMIN"
                        },
                        new
                        {
                            Id = "98f4df00-a720-4794-bacb-921996ae6d22",
                            ConcurrencyStamp = "294d9109-735e-4481-9754-52c8b4c87ed8",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "7de9e0d6-7698-454c-8093-f5cc111bc251",
                            ConcurrencyStamp = "45259077-663d-4409-ab4b-aab2da1d5d27",
                            Name = "Parent",
                            NormalizedName = "PARENT"
                        },
                        new
                        {
                            Id = "c04651d9-82f3-4096-951c-cfa33d654382",
                            ConcurrencyStamp = "0fa3dc95-f069-4e0b-9d6e-aa7370bbcb73",
                            Name = "Teacher",
                            NormalizedName = "TEACHER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", "security");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", "security");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", "security");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", "security");

                    b.HasData(
                        new
                        {
                            UserId = "31784be6-9506-4e3f-a4d2-a9ba79689376",
                            RoleId = "c7dedf49-21a9-4f26-8c00-eadd86eb812f"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", "security");
                });

            modelBuilder.Entity("SchoolAttendanceSystem.DAL.Entities.Auth.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("Users", "security");

                    b.HasData(
                        new
                        {
                            Id = "31784be6-9506-4e3f-a4d2-a9ba79689376",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "be424d00-35a1-4cc8-97de-559fb42cd92e",
                            Email = "superadmin@superadmin.ibnkhaldun",
                            EmailConfirmed = false,
                            FullName = "superadmin",
                            LockoutEnabled = false,
                            NormalizedEmail = "SUPERADMIN@SUPERADMIN.IBNKHALDUN",
                            NormalizedUserName = "SUPERADMIN@SUPERADMIN.IBNKHALDUN",
                            PasswordHash = "AQAAAAEAACcQAAAAEIH6S+TM+CzS8uRLpq7Qo7unTY8cQniHZZ1JDL6VrO0e0eP5D9q8WiPowUWsYm+ffQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "342b6a16-6b50-49a6-8fac-0dcbe477c8a8",
                            TwoFactorEnabled = false,
                            UserName = "superadmin@superadmin.ibnkhaldun"
                        });
                });

            modelBuilder.Entity("SchoolAttendanceSystem.DAL.Entities.Domain.Class", b =>
                {
                    b.Property<string>("ClassName")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.HasKey("ClassName");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("SchoolAttendanceSystem.DAL.Entities.Domain.Log", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AttendanceStateId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("LogTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AttendanceStateId");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("SchoolAttendanceSystem.DAL.Entities.Domain.Parent", b =>
                {
                    b.Property<string>("ParentId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Address")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ExternalEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Governorate")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Job")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nid")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ParentId");

                    b.ToTable("Parents");
                });

            modelBuilder.Entity("SchoolAttendanceSystem.DAL.Entities.Domain.Student", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ClassCode")
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ClassCode");

                    b.HasIndex("ParentId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("SchoolAttendanceSystem.DAL.Entities.Domain.StudentAttendanceState", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DateOfDay")
                        .HasColumnType("Date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.ToTable("StudentAttendanceStates");
                });

            modelBuilder.Entity("SchoolAttendanceSystem.DAL.Entities.Domain.StudyingDay", b =>
                {
                    b.Property<string>("DayCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasColumnType("nvarchar(3)");

                    b.HasKey("DayCode");

                    b.HasIndex("ClassName");

                    b.ToTable("StudyingDays");
                });

            modelBuilder.Entity("SchoolAttendanceSystem.DAL.Entities.Domain.StudyPeriod", b =>
                {
                    b.Property<string>("PeriodCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DayCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PeriodName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubjectCode")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("PeriodCode");

                    b.HasIndex("DayCode");

                    b.HasIndex("SubjectCode");

                    b.ToTable("StudyPeriods");
                });

            modelBuilder.Entity("SchoolAttendanceSystem.DAL.Entities.Domain.Subject", b =>
                {
                    b.Property<string>("SubjectCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ClassName")
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("SubjcetName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeacherId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("SubjectCode");

                    b.HasIndex("ClassName");

                    b.HasIndex("TeacherId");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("SchoolAttendanceSystem.DAL.Entities.Domain.Teacher", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Address")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Governorate")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Specialize")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("SchoolAttendanceSystem.DAL.Entities.Auth.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("SchoolAttendanceSystem.DAL.Entities.Auth.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolAttendanceSystem.DAL.Entities.Auth.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("SchoolAttendanceSystem.DAL.Entities.Auth.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SchoolAttendanceSystem.DAL.Entities.Domain.Log", b =>
                {
                    b.HasOne("SchoolAttendanceSystem.DAL.Entities.Domain.StudentAttendanceState", "StudentAttendanceState")
                        .WithMany("Logs")
                        .HasForeignKey("AttendanceStateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StudentAttendanceState");
                });

            modelBuilder.Entity("SchoolAttendanceSystem.DAL.Entities.Domain.Parent", b =>
                {
                    b.HasOne("SchoolAttendanceSystem.DAL.Entities.Auth.User", "User")
                        .WithMany("Parents")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SchoolAttendanceSystem.DAL.Entities.Domain.Student", b =>
                {
                    b.HasOne("SchoolAttendanceSystem.DAL.Entities.Domain.Class", "Class")
                        .WithMany("Students")
                        .HasForeignKey("ClassCode");

                    b.HasOne("SchoolAttendanceSystem.DAL.Entities.Domain.Parent", "Parent")
                        .WithMany("Students")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("SchoolAttendanceSystem.DAL.Entities.Domain.StudentAttendanceState", b =>
                {
                    b.HasOne("SchoolAttendanceSystem.DAL.Entities.Domain.Student", "Student")
                        .WithMany("AttendanceStates")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("SchoolAttendanceSystem.DAL.Entities.Domain.StudyingDay", b =>
                {
                    b.HasOne("SchoolAttendanceSystem.DAL.Entities.Domain.Class", "Class")
                        .WithMany("StudyingDays")
                        .HasForeignKey("ClassName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");
                });

            modelBuilder.Entity("SchoolAttendanceSystem.DAL.Entities.Domain.StudyPeriod", b =>
                {
                    b.HasOne("SchoolAttendanceSystem.DAL.Entities.Domain.StudyingDay", "Day")
                        .WithMany("Periods")
                        .HasForeignKey("DayCode");

                    b.HasOne("SchoolAttendanceSystem.DAL.Entities.Domain.Subject", "Subject")
                        .WithMany("Periods")
                        .HasForeignKey("SubjectCode");

                    b.Navigation("Day");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("SchoolAttendanceSystem.DAL.Entities.Domain.Subject", b =>
                {
                    b.HasOne("SchoolAttendanceSystem.DAL.Entities.Domain.Class", "Class")
                        .WithMany()
                        .HasForeignKey("ClassName");

                    b.HasOne("SchoolAttendanceSystem.DAL.Entities.Domain.Teacher", "Teacher")
                        .WithMany("Subjects")
                        .HasForeignKey("TeacherId");

                    b.Navigation("Class");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("SchoolAttendanceSystem.DAL.Entities.Domain.Teacher", b =>
                {
                    b.HasOne("SchoolAttendanceSystem.DAL.Entities.Auth.User", "User")
                        .WithMany("Teachers")
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SchoolAttendanceSystem.DAL.Entities.Auth.User", b =>
                {
                    b.Navigation("Parents");

                    b.Navigation("Teachers");
                });

            modelBuilder.Entity("SchoolAttendanceSystem.DAL.Entities.Domain.Class", b =>
                {
                    b.Navigation("Students");

                    b.Navigation("StudyingDays");
                });

            modelBuilder.Entity("SchoolAttendanceSystem.DAL.Entities.Domain.Parent", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("SchoolAttendanceSystem.DAL.Entities.Domain.Student", b =>
                {
                    b.Navigation("AttendanceStates");
                });

            modelBuilder.Entity("SchoolAttendanceSystem.DAL.Entities.Domain.StudentAttendanceState", b =>
                {
                    b.Navigation("Logs");
                });

            modelBuilder.Entity("SchoolAttendanceSystem.DAL.Entities.Domain.StudyingDay", b =>
                {
                    b.Navigation("Periods");
                });

            modelBuilder.Entity("SchoolAttendanceSystem.DAL.Entities.Domain.Subject", b =>
                {
                    b.Navigation("Periods");
                });

            modelBuilder.Entity("SchoolAttendanceSystem.DAL.Entities.Domain.Teacher", b =>
                {
                    b.Navigation("Subjects");
                });
#pragma warning restore 612, 618
        }
    }
}
